### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by djoudi** [3x1io/filament-translations#10]
TypeError
Filament\Navigation\NavigationItem::url(): Argument #1 ($url) must be of type Closure|string|null, Illuminate\Routing\UrlGenerator given, called in C:\Users\info\apps\demande\vendor\3x1io\filament-translations\src\FilamentTranslationsProvider.php on line 37

**Comment by silentridge** [comment]
i had the same issue and found two solutions. First is to hack around it by changing that line:
```
 ->url(url(config('filament-translations.languages-switcher-menu.url'))),
```
to 
```
 ->url(config('filament-translations.languages-switcher-menu.url')),
```
and import as local package.

But the other one is a bit better, in config file: `"show-switcher" => false,` also solves the issue.

**Comment by fadymondy** [comment]
done please update
