### ISSUE TITLE
Change Language button is not translatable

### ISSUE THREAD

**Issue by Odilbukh** [3x1io/filament-translations#11]
I have translated all fields on Translations page. You can see it on first image. It works good but button "Change Language" is not changing when I switch language. Even I have translate "menu" field in tranlation.php

Pls help to fix it

![image](https://user-images.githubusercontent.com/22895615/173364425-b53c423b-b56b-4b18-bcfe-b253983d73b5.png)

![image](https://user-images.githubusercontent.com/22895615/173364500-fa62b7b9-e4c0-4cd0-bdb1-603b970d18a1.png)

**Comment by fadymondy** [comment]
it's done please update
