### ISSUE TITLE
How to move "Change Language" from sidebar to user-menu dropdown menu?

### ISSUE THREAD

**Issue by Odilbukh** [3x1io/filament-translations#12]
Pls help me to move button "Change Language" from sidebar to user-menu dropdown menu
Thanks!

![image](https://user-images.githubusercontent.com/22895615/173507880-6c9c9990-b199-4de6-94e7-0054bda9296f.png)

**Comment by fadymondy** [comment]
you can change it by adding to config 

```php
    "languages-switcher-menu" => [
        "group" => "Translations",
        "icon" => "heroicon-o-translate",
        "sort" => 10,
        "url" => 'admin/translations/change',
        "position" => "user" //[user|navigation]
    ],
```
