### ISSUE TITLE
Move scan to background task [v2.xx]

### ISSUE THREAD

**Issue by TKrisee** [3x1io/filament-translations#13]
Firs off, thanks for the amazing work on this package! Could you make some changes to the "Scan" function so that it runs in the background maybe as a job or as a command? Better yet maybe a config entry for this? Currently it's impossible to run it on Vapor because the request simply times out.

Again, thanks for the amazing work!

**Comment by fadymondy** [comment]
oky i will add it to the next version

**Comment by fadymondy** [comment]
you can use the new version to support filamentv3

https://www.github.com/tomatophp/filament-translations
