### ISSUE TITLE
Shield can't guard translations

### ISSUE THREAD

**Issue by ShaungBhone** [3x1io/filament-translations#15]
In my app, I'm using [shield](https://filamentphp.com/plugins/shield) and filament-translation. Shield middleware doesn't work only for filament-translation. I turn off the translation model for users in shield resources but users can accept translation.

- When you see this issue I can explain more details. Thank you.

**Comment by fadymondy** [comment]
you can use the new version to support filamentv3

https://www.github.com/tomatophp/filament-translations
