### ISSUE TITLE
Missing translation name

### ISSUE THREAD

**Issue by loranger** [3x1io/filament-translations#17]
Hi,

I did setup this awesome plugin in my filament admint, but I miss my translation name to be displayed.

Here is a part of my `filament-translations.php` file:

```php
    'locals' => [
        'en' => 'English',
        'fr' => 'Français',
        'pt_BR' => 'Português (Brasil)',
    ],
```

But my translation admin still misses the french name (and this one only) and displays `filament-translations::translation.lang.fr` instead:

<img width="864" alt="SCR-20230318-otgf" src="https://user-images.githubusercontent.com/6014/226116048-b00d4440-9e8e-48c1-bfed-377c6296233c.png">

What did I miss ?

**Comment by fadymondy** [comment]
you can use the new version to support filamentv3

https://www.github.com/tomatophp/filament-translations
