### ISSUE TITLE
can i add  certain role to see traslation menu item

### ISSUE THREAD

**Issue by mahmoudelgharabawi** [3x1io/filament-translations#19]
i just want to any user in admin panel can change language from arabic to english and vice versa But only one admin with role super admin can delete and edit translation 
is it possible ?! as i try But found no way until now

**Comment by mahmoudelgharabawi** [comment]
???!!!!

**Comment by fadymondy** [comment]
you can use the new version to support filamentv3

https://www.github.com/tomatophp/filament-translations
